# Ejercicio 1

In [8]:
import numpy as np

matrix = numpy.array([[2/3, -1/3, -1/3], [-1/3, 2/3, -1/3], [-1/3, -1/3, 2/3]])

print(matrix)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]


In [6]:
idempotent = matrix @ matrix
print(idempotent)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]


In [10]:
if (np.allclose(matrix, idempotent)):
    print("La matriz es idempotente")

La matriz es idempotente


In [11]:
a = np.array([[1, 3 ,2], [4, 2, -1], [5, 5, 1]])

print(a)

[[ 1  3  2]
 [ 4  2 -1]
 [ 5  5  1]]


In [15]:
autovalores = np.linalg.eigvals(a)
print(np.round(autovalores))

[ 6. -2.  0.]


In [26]:
print(a @ np.array([5/3, 1, 8/3]))
print(a @ np.array([1/np.sqrt(2), -1/np.sqrt(2), 0]))
print(a @ np.array([-1, 1, 0]))

[10.  6. 16.]
[-1.41421356  1.41421356  0.        ]
[ 2 -2  0]


In [24]:
b = np.array([[1, 3 ,2], [4, 2, -1], [5, 5, 1]])
identidad = np.eye(3)*6
print(identidad)

rango = np.linalg.matrix_rank(b - identidad)

multiplicidad = len(b) - rango
print(multiplicidad)

[[6. 0. 0.]
 [0. 6. 0.]
 [0. 0. 6.]]
1
