In [1]:
import numpy as np

matrix_a = np.array([[1, 2, -1, 0], [2, 3, 1, 6], [0, 1, 0, 1]])

print(matrix_a)

[[ 1  2 -1  0]
 [ 2  3  1  6]
 [ 0  1  0  1]]


In [ ]:
u, s, vh = np.linalg.svd(matrix_a)

print("U:\n", u)
print("S:\n", s)
print("Vh:\n", vh)

U:
 [[ 0.15315131  0.97666775 -0.15054825]
 [ 0.9719684  -0.17637797 -0.15546141]
 [ 0.17838754  0.12251902  0.97630271]]
S:
 [7.26324773 2.23310342 0.50841079]
Vh:
 [[ 0.28872595  0.46819212  0.11273429  0.82748078]
 [ 0.27939226  0.69263278 -0.51634229 -0.41903514]
 [-0.90767362  0.41073475 -0.00966377  0.08562808]
 [-0.12126781 -0.36380344 -0.84887469  0.36380344]]


In [3]:
a_daga = np.linalg.pinv(matrix_a)

print("A^+:\n", a_daga)

A^+:
 [[ 0.39705882  0.29411765 -1.72058824]
 [ 0.19117647 -0.11764706  0.83823529]
 [-0.22058824  0.05882353 -0.04411765]
 [-0.19117647  0.11764706  0.16176471]]


In [4]:
x = np.array([1, 2, 3])

print(x.T)

print("A^+ * x:\n", a_daga @ x.T)

[1 2 3]
A^+ * x:
 [-4.17647059  2.47058824 -0.23529412  0.52941176]
