In [25]:
import numpy as np

# Capa 1
w_1 = np.array([[0.1, -0.5], [-0.3, -0.9], [0.8, 0.02]])
b_1 = np.array([[0.1], [0.5], [0.8]])

# Capa 2
w_2 = np.array([[-0.4, 0.2, -0.5]])
b_2 = np.array([[0.7]])

# Valores de entrada y etiqueta real
x = np.array([[1.8], [-3.4]])
y = np.array([[5]])

print(w_1)
print(b_1)
print(w_2)
print(b_2)
print(x)

[[ 0.1  -0.5 ]
 [-0.3  -0.9 ]
 [ 0.8   0.02]]
[[0.1]
 [0.5]
 [0.8]]
[[-0.4  0.2 -0.5]]
[[0.7]]
[[ 1.8]
 [-3.4]]


In [16]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1 - s)

def loss(y, y_hat):
    return ((y - y_hat) ** 2) / 2

def loss_derivative(y, y_hat):
    return y_hat - y

In [20]:
# Forward pass
z_1 = w_1 @ x + b_1
y_1 = sigmoid(z_1)

z_2 = w_2 @ y_1 + b_2
y_2 = sigmoid(z_2)[0, 0]

loss_value = loss(y, y_2)


In [26]:
# Backward pass
dy2 = loss_derivative(y, y_2)
dz2 = dy2 * sigmoid_derivative(z_2)[0, 0]

dy1 = w_2.T @ dz2
dz1 = dy1 * sigmoid_derivative(z_1)
db_2 = dz2

print(db_2)

[[-1.11707367]]


In [28]:
dw_2 = dz2 * y_1.T
dw_1 = dz1 @ x.T

print(dw_2)
print(dw_1)

[[-0.98155159 -1.0650957  -1.0028046 ]]
[[ 0.0857381  -0.16194975]
 [-0.01784139  0.0337004 ]
 [ 0.09232211 -0.1743862 ]]
